### ISSUE TITLE
ssm-list not showing complete server list

### ISSUE THREAD

**Issue by iniquityx2** [Vonage/aws-systems-manager-toolkit#1]
It looks like the ssm-list command is only showing 8 host in an account where we have 23 ssm enabled host.

Using the cli call of aws ssm get-inventory it shows the 23 host correctly.

If I use ssm-connect I can properly connect to a host not listed by ssm-list

**Comment by JustinTangg** [comment]
This was a syntax issue fixed in https://github.com/Vonage/aws-systems-manager-toolkit/commit/55af243c90fa31829907d29ab6da2656f43909e4. I also added code to handle an instance not existing but still getting returned as not terminated in ssm.
